# Generated by Omarchy from the active theme's colors.toml.
# Sourced by ~/.config/tmux/tmux.conf before catppuccin loads, so these win
# (catppuccin sets its palette with `set -ogq`, i.e. only-if-unset).

set -g @thm_bg        "{{ background }}"
set -g @thm_fg        "{{ foreground }}"
set -g @thm_mantle    "{{ color0 }}"
set -g @thm_crust     "{{ color0 }}"
set -g @thm_surface_0 "{{ color0 }}"
set -g @thm_surface_1 "{{ color8 }}"
set -g @thm_surface_2 "{{ color8 }}"
set -g @thm_overlay_0 "{{ color8 }}"
set -g @thm_overlay_1 "{{ color8 }}"
set -g @thm_overlay_2 "{{ color8 }}"
set -g @thm_subtext_0 "{{ foreground }}"
set -g @thm_subtext_1 "{{ foreground }}"
set -g @thm_yellow    "{{ color3 }}"
set -g @thm_peach     "{{ color1 }}"
set -g @thm_red       "{{ color1 }}"
set -g @thm_maroon    "{{ color1 }}"
set -g @thm_green     "{{ color2 }}"
set -g @thm_teal      "{{ color6 }}"
set -g @thm_sky       "{{ color6 }}"
set -g @thm_sapphire  "{{ color6 }}"
set -g @thm_blue      "{{ color4 }}"
set -g @thm_lavender  "{{ color4 }}"
set -g @thm_mauve     "{{ color5 }}"
set -g @thm_pink      "{{ color5 }}"
set -g @thm_flamingo  "{{ accent }}"
set -g @thm_rosewater "{{ accent }}"

# Pane borders follow the theme too.
set -g pane-active-border-style "fg={{ accent }},bg=default"
set -g pane-border-style "fg={{ color8 }},bg=default"
