#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/ghostty
ln -s $DOTFILES/ghostty $HOME/.config/ghostty

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/sketchybar
ln -s $DOTFILES/sketchybar $HOME/.config/sketchybar

rm -rf $HOME/.config/skhd
ln -s $DOTFILES/skhd $HOME/.config/skhd

rm -rf $HOME/.config/yabai
ln -s $DOTFILES/yabai $HOME/.config/yabai
