#!/usr/bin/env bash

# This is still work in progress. Not finished at all!

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/ghostty
ln -s $DOTFILES/ghostty $HOME/.config/ghostty

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin
rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/vim
ln -s $DOTFILES/vim $HOME/.config/vim

rm -rf $HOME/.config/sketchybar
ln -s $DOTFILES/sketchybar $HOME/.config/sketchybar

rm -rf $HOME/.config/yabai
ln -s $DOTFILES/yabai $HOME/.config/yabai

rm -rf $HOME/.config/skhd
ln -s $DOTFILES/skhd $HOME/.config/skhd

# Services
brew install yabai sketchybar skhd jq

# Fonts
brew install --cask sf-symbols
brew install --cask font-hack-nerd-font
curl -L https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v1.0.3/sketchybar-app-font.ttf -o $HOME/Library/Fonts/sketchybar-app-font.ttf

# Script for Sketchybar project - [] TODO
# curl -L https://developer.apple.com/download/files/SF-Pro.dmg
